### ISSUE TITLE
Support Stable Diffusion inpainting

### ISSUE THREAD

**Issue by mvkvc** [elixir-nx/bumblebee#212] opened 2023-05-21 17:55 UTC
I would like to use the SD 2 inpainting model from https://huggingface.co/stabilityai/stable-diffusion-2-inpainting with Bumblebee. From reviewing the code it doesn't seem like there is support for this as of yet and I would like to add it if possible.

**Comment by josevalim** [comment] 2023-05-21 17:58
PRs certainly welcome!

**Comment by josevalim** [comment] 2023-09-12 13:16
Dupe of #120.

**Closed by josevalim** 2023-09-12 13:16 UTC
